[package]
name = "schema-gen"
version = "0.1.0"
edition = "2021"


[dependencies]
radix-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0", features = [
    "serde",
] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0", features = [
    "serde",
] }
radix-transactions = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0" }
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.3.0", features = [
    "serde",
] }
hex = "0.4.3"
clap = { version = "4.5.35", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json", "blocking"] }
serde_json = "1.0.140"
vercel_runtime = { version = "1" }
tokio = { version = "1", features = ["macros"] }
serde = "1.0.219"

[[bin]]
name = "handler"
path = "api/handler.rs"
